apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: eu.zetanova.csi.hyperv
  namespace: csi-hyperv
spec:
  attachRequired: true
  #podInfoOnMount: true
  #fsGroupPolicy: File # added in Kubernetes 1.19, this field is GA as of Kubernetes 1.23
  #volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    #- Persistent
    #- Ephemeral
  #tokenRequests: # added in Kubernetes 1.20. See status at https://kubernetes-csi.github.io/docs/token-requests.html#status
    #- audience: "gcp"
    #- audience: "" # empty string means defaulting to the `--api-audiences` of kube-apiserver
    #  expirationSeconds: 3600
  #requiresRepublish: true # added in Kubernetes 1.20. See status at https://kubernetes-csi.github.io/docs/token-requests.html#status