apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hyperv-sc # defined in csi-storageclass.yaml